import type { SimulationPattern, PatternPreset } from '@/types/browser';

export const PATTERN_PRESETS: Record<SimulationPattern, PatternPreset> = {
  idle: {
    label: 'Idle',
    description: 'Device at rest',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 0 },
    accelAmplitude: { x: 0.02, y: 0.02, z: 0.02 },
    gyroAmplitude: { x: 0.001, y: 0.001, z: 0.001 },
    freq: 0.5,
  },
  walking: {
    label: 'Walk',
    description: 'Normal walking',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 0 },
    accelAmplitude: { x: 1.2, y: 2.5, z: 3.0 },
    gyroAmplitude: { x: 0.3, y: 0.2, z: 0.15 },
    freq: 1.8,
  },
  running: {
    label: 'Run',
    description: 'Jogging pace',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 0 },
    accelAmplitude: { x: 3.0, y: 5.0, z: 6.0 },
    gyroAmplitude: { x: 0.8, y: 0.6, z: 0.4 },
    freq: 2.8,
  },
  shake: {
    label: 'Shake',
    description: 'Vigorous shake',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 0 },
    accelAmplitude: { x: 12.0, y: 8.0, z: 4.0 },
    gyroAmplitude: { x: 2.0, y: 2.5, z: 1.5 },
    freq: 8.0,
  },
  rotate: {
    label: 'Rotate',
    description: '360° rotation',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 1.0 },
    accelAmplitude: { x: 4.9, y: 4.9, z: 2.0 },
    gyroAmplitude: { x: 0.2, y: 0.2, z: 0.5 },
    freq: 0.3,
  },
  freefall: {
    label: 'Fall',
    description: 'Freefall sim',
    baseAccel: { x: 0, y: 0, z: 0.5 },
    baseGyro: { x: 0.5, y: 0.3, z: 0.2 },
    accelAmplitude: { x: 0.3, y: 0.3, z: 0.5 },
    gyroAmplitude: { x: 0.5, y: 0.5, z: 0.5 },
    freq: 2.0,
  },
  driving: {
    label: 'Drive',
    description: 'In-vehicle',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 0 },
    accelAmplitude: { x: 0.8, y: 1.5, z: 0.5 },
    gyroAmplitude: { x: 0.05, y: 0.08, z: 0.15 },
    freq: 0.4,
  },
  custom: {
    label: 'Custom',
    description: 'User-defined',
    baseAccel: { x: 0, y: 0, z: 9.8 },
    baseGyro: { x: 0, y: 0, z: 0 },
    accelAmplitude: { x: 2.0, y: 2.0, z: 2.0 },
    gyroAmplitude: { x: 0.5, y: 0.5, z: 0.5 },
    freq: 1.0,
  },
};
